[package]
name = "realpath-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "realpath"
path = "src/lib.rs"
types = ["cdylib" , "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-absolutize = "*"

